// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DbSeedingContext))]
    partial class DbSeedingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Card Content 1",
                            Title = "Cad Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Card Content 2",
                            Title = "Cad Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Card Content 3",
                            Title = "Cad Title 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Card Content 4",
                            Title = "Cad Title 4"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Desc 1",
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Desc 2",
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Desc 3",
                            Title = "Title 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
